# Generated by Django 4.1.3 on 2022-11-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='initial',
        ),
    ]
